[package]
name = "iced-todos"
version = "0.1.1"
edition = "2021"

[lints.rust]
unsafe_code = "warn"
dead_code = "warn"

[lints.clippy]
pedantic = "deny"
correctness = "deny"
suspicious = "warn"
complexity = "warn"
style = "warn"
nursery = "deny"
all = "warn"

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
csv = "1.3.0"
log = "0.4.21"
log4rs = "1.3.0"

[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
rev = "8bfd099c5929d927a3fdde666d4c645d0bd83cb7"

